title: 我的导航
description: 个人网络导航站
author: 徐紫阳
favicon: favicon.ico
logo_text: 导航站

fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
    
profile:
  title: Hello,
  subtitle: Welcome to My Navigation
  description: 个人链接导航站

social:
  - name: GitHub
    url: https://github.com/xzyyyyyyyyyyy
    icon: fab fa-github
  - name: QQ
    url: https://qm.qq.com/cgi-bin/qm/qr?k=9ymuJO7BQh8kIeiFtOZjorRXvoJb1a_Q
    icon: fab fa-qq